import { GoogleGenAI } from '@google/genai'
import { NextRequest } from 'next/server'
import { asClaims, failedClaim, judgePrompt, jsonLine, maxInput, mergeSources, normalizeJudge, parseJson, sanitizeText, scoreClaim, splitterPrompt, timeout, uniqueClaims, modelName, streamMime } from '@/lib/scoring'
import { saveAnalysis } from '@/lib/supabase'
export const runtime='nodejs'
const ai=()=>new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY||''})
async function generate(contents:string,tools?:any[]){return ai().models.generateContent({model:modelName,contents,config:tools?{tools}:undefined})}
export async function POST(req:NextRequest){let body:unknown;try{body=await req.json()}catch{return new Response(JSON.stringify({message:'Invalid request.'}),{status:400})} const text=sanitizeText(typeof (body as any)?.text==='string'?(body as any).text:'');if(!text||text.length>maxInput)return new Response(JSON.stringify({message:`Enter between 1 and ${maxInput.toLocaleString()} characters.`}),{status:400}); const encoder=new TextEncoder();let controller!:ReadableStreamDefaultController;const stream=new ReadableStream({start(c){controller=c;void run(text,c,encoder)}});return new Response(stream,{headers:{'Content-Type':streamMime,'Cache-Control':'no-cache'}})}
async function run(text:string,c:ReadableStreamDefaultController,encoder:TextEncoder){const send=(x:unknown)=>c.enqueue(encoder.encode(jsonLine(x)));let claims:string[]=[];try{let parsed;try{parsed=parseJson((await generate(`${splitterPrompt}\n\nTEXT:\n${text}`)).text||'')}catch{parsed=parseJson((await generate(`${splitterPrompt}\nReturn only the JSON object.\n\nTEXT:\n${text}`)).text||'')}claims=uniqueClaims(asClaims(parsed));send({type:'claims',claims});if(!claims.length){const id=await saveAnalysis(text,[]);send({type:'done',id});c.close();return}const results=await Promise.all(claims.map(async(claim,index)=>{try{const response=await timeout(generate(judgePrompt(claim),[{googleSearch:{}}]),30000);const judge=mergeSources(normalizeJudge(parseJson(response.text||'{}')),response.candidates?.[0]?.groundingMetadata);const result=scoreClaim(claim,judge);send({type:'verdict',index,result});return result}catch(e){const result=failedClaim(claim);send({type:'verdict',index,result});send({type:'error',index,message:'Search failed for this claim.'});return result}}));const id=await saveAnalysis(text,results);send({type:'done',id});c.close()}catch(e){send({type:'error',message:'The analysis could not be completed. Try again.'});c.close()}}
